-- Seed del menú generado desde mock-menu.ts (scripts/gen-seed.ts).
-- Idempotente: upsert por id. Correr DESPUÉS de la migración 0001_init.sql.

insert into public.menu_items
  (id, slug, name, description, price_in_cents, currency, images, available, max_quantity, category, type, servings, includes, metadata, sort_order)
values
  ('pic-encuentro', 'picada-encuentro', 'Picada Encuentro', 'Jamón cocido y crudo, salamín fino, bondiola y mortadela con pistacho. 3 quesos (pategrás, ají molido y azul). Hummus de garbanzo y de morrón, tostaditas, aceitunas, frutas de estación y frutos secos.', 8900000, 'ARS', '[{"url":"/photos/picada-encuentro-1.jpg","alt":"Picada Encuentro — Umami Bites Catering"},{"url":"/photos/picada-encuentro-2.jpg","alt":"Picada Encuentro — Umami Bites Catering"},{"url":"/photos/picada-encuentro-3.jpg","alt":"Picada Encuentro — Umami Bites Catering"}]'::jsonb, true, 10, 'Picadas', 'package', 6, '["Fiambres: jamón cocido, jamón crudo, salamín fino, bondiola, mortadela con pistacho","Quesos: pategrás, ají molido, azul","Hummus de garbanzo y limón + hummus de morrón","Tostaditas saborizadas con finas hierbas","Aceitunas, frutas de estación y frutos secos"]'::jsonb, '{"tagline":"Comen 6 · pican 10","tierMayor":"$120.000 — comen 8 / pican 12","unit":"tabla"}'::jsonb, 0),
  ('pic-umami', 'picada-umami', 'Picada Umami', 'La especialidad de la casa. 6 fiambres premium (jamón crudo, bondiola, longaniza, salamines), 5 quesos (brie, rockefort, pategrás, ají y pimentón, pimienta negra), dips caseros, tostaditas, batatitas, frutas y frutos secos.', 18000000, 'ARS', '[{"url":"/photos/picada-umami-1.jpg","alt":"Picada Umami — Umami Bites Catering"},{"url":"/photos/picada-umami-2.jpg","alt":"Picada Umami — Umami Bites Catering"},{"url":"/photos/picada-umami-3.jpg","alt":"Picada Umami — Umami Bites Catering"},{"url":"/photos/picada-umami-4.jpg","alt":"Picada Umami — Umami Bites Catering"}]'::jsonb, true, 6, 'Picadas', 'package', 10, '["6 fiambres premium incl. bondiola y longaniza","5 quesos incl. brie y rockefort","Dips caseros: berenjena, ciboulette, hummus de morrón","Tostaditas saborizadas, pan de campo y batatitas fritas","Aceitunas, frutas frescas y frutos secos"]'::jsonb, '{"tagline":"Comen 10 · pican 20","tierMayor":"$270.000 — comen 15 / pican 30","especialidad":"true","unit":"tabla"}'::jsonb, 1),
  ('emp-saltenas', 'empanadas-saltenas', 'Empanadas (docena)', 'Carne cortada a cuchillo (salteñas), caprese, verdura y humita. Congeladas o horneadas a elección. Mínimo 1 docena.', 2600000, 'ARS', '[{"url":"/photos/empanadas-1.jpg","alt":"Empanadas (docena) — Umami Bites Catering"}]'::jsonb, true, 30, 'Empanadas', 'dish', null, null, '{"unit":"docena","estado":"Congeladas o horneadas a elección"}'::jsonb, 2),
  ('emp-canastitas', 'canastitas-surtidas', 'Canastitas (1/2 docena)', 'De verdura y de jamón y queso. Congeladas o horneadas a elección. Mínimo 6 unidades por variedad.', 1300000, 'ARS', '[{"url":"/photos/empanadas-1.jpg","alt":"Canastitas (1/2 docena) — Umami Bites Catering"}]'::jsonb, true, 30, 'Empanadas', 'dish', null, null, '{"unit":"1/2 docena","estado":"Congeladas o horneadas a elección"}'::jsonb, 3),
  ('ff-shots-guacamole', 'shots-guacamole-nachos', 'Shots de guacamole y nachos (x12)', 'Guacamole fresco en shots individuales con nachos crocantes, más nachos extra en canastita.', 1600000, 'ARS', '[{"url":"/photos/shots-guacamole.jpg","alt":"Shots de guacamole y nachos (x12) — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"docena"}'::jsonb, 4),
  ('ff-brusquetas', 'brusquetas-surtidas', 'Brusquetas a elección (x24)', 'A elección: jamón crudo y rúcula; mix de verduras; pera, queso azul, nuez y miel; cebolla caramelizada. 12 de cada variedad.', 1800000, 'ARS', '[{"url":"/photos/p22.jpg","alt":"Brusquetas a elección (x24) — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"pack"}'::jsonb, 5),
  ('ff-tarteletas', 'tarteletas-queso-azul-nuez', 'Tarteletas de queso azul y nuez (x24)', 'Mini tarteletas de queso azul y nuez y/o de pasta de aceitunas. Mínimo 24 unidades.', 1800000, 'ARS', '[{"url":"/photos/p03.jpg","alt":"Tarteletas de queso azul y nuez (x24) — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"pack"}'::jsonb, 6),
  ('ff-salchichas', 'salchichas-copetin-vino', 'Salchichas de copetín al vino tinto (x24)', 'Salchichas de copetín glaseadas al vino tinto. Mínimo 24 unidades.', 1600000, 'ARS', '[{"url":"/photos/p28.jpg","alt":"Salchichas de copetín al vino tinto (x24) — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"pack"}'::jsonb, 7),
  ('ff-pinchos-cherry', 'pinchos-tomate-cherry', 'Pinchos de tomate cherry (x12)', 'Tomate cherry, queso y albahaca fresca en pinchos individuales.', 900000, 'ARS', '[{"url":"/photos/pinchos-cherry.jpg","alt":"Pinchos de tomate cherry (x12) — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"docena"}'::jsonb, 8),
  ('ff-camembert-castanas', 'camembert-castanas-miel', 'Camembert con castañas y miel', 'Queso camembert acompañado de castañas de cajú y un hilo de miel.', 2200000, 'ARS', '[{"url":"/photos/camembert-1.jpg","alt":"Camembert con castañas y miel — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"porción"}'::jsonb, 9),
  ('ff-flor-papas', 'flor-de-papas', 'Flor de papas', 'Papas Pringles en flor sobre pasta de queso blanco saborizado.', 1000000, 'ARS', '[{"url":"/photos/flor-de-papas.jpg","alt":"Flor de papas — Umami Bites Catering"}]'::jsonb, true, 20, 'Complementos', 'dish', null, null, '{"unit":"porción"}'::jsonb, 10),
  ('menu-carnes-desmechadas', 'menu-carnes-desmechadas', 'Menú "Carnes desmechadas"', 'Sandwichitos de carne vacuna y barbacoa y/o bondiola desmechada al vino tinto, con salsas caseras (queso crema y verdeo, mayonesa de berenjena, mayonesa de ajo, hummus de garbanzo y de morrón, pasta de aceitunas). Con recepción de mesa de campo: tabla de fiambres y quesos, empanadas criollas, dips, brusquetas y mini tarteletas.', 34000000, 'ARS', '[{"url":"/photos/carnes-desmechadas-1.jpg","alt":"Menú \"Carnes desmechadas\" — Umami Bites Catering"},{"url":"/photos/carnes-desmechadas-2.jpg","alt":"Menú \"Carnes desmechadas\" — Umami Bites Catering"}]'::jsonb, true, 20, 'Menús', 'package', 20, '["Recepción: mesa de campo completa","Empanadas criollas y dips caseros","Sandwichitos de carne y barbacoa / bondiola al vino tinto","6 salsas a elección"]'::jsonb, '{"unit":"menú","tagline":"Menú para ~20 personas","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 11),
  ('menu-todo-sandwich', 'menu-todo-sandwich', 'Menú "Todo sándwich a la parrilla"', 'Servicio en domicilio. Recepción con mesa de campo y sándwich de chorizo a la parrilla. La comida: sandwichitos en pan de figaza de manteca de lomo y carré de cerdo, acompañados de 3 salsas (agridulce de ciruela y mostaza, criolla, mayonesa de ajo y cebolla de verdeo) y otros aderezos.', 3800000, 'ARS', '[{"url":"/photos/todo-sandwich-1.jpg","alt":"Menú \"Todo sándwich a la parrilla\" — Umami Bites Catering"},{"url":"/photos/todo-sandwich-2.jpg","alt":"Menú \"Todo sándwich a la parrilla\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Recepción: mesa de campo + sándwich de chorizo a la parrilla","Sandwichitos de lomo y carré de cerdo en pan de figaza","3 salsas + aderezos","Incluye servicio en domicilio"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","servicio":"Servicio en domicilio","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 12),
  ('menu-asado', 'menu-asado-al-asador', 'Menú "Asado al asador"', 'Mesa de campo premium de recepción (fiambres, quesos, empanadas criollas y sándwich de chorizo bombón). La comida: 2 ensaladas a elección (clásica o gourmet), achuras (morcilla y mollejas al limón) y asado de vacío y costillar al asador según espacio disponible. Postre a elección.', 5500000, 'ARS', '[{"url":"/photos/asado-1.jpg","alt":"Menú \"Asado al asador\" — Umami Bites Catering"},{"url":"/photos/asado-2.jpg","alt":"Menú \"Asado al asador\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Mesa de campo premium de recepción","2 ensaladas a elección (clásica / gourmet)","Achuras: morcilla y mollejas al limón","Asado: vacío y costillar al asador","Postre a elección: flan casero con DDL o brownie con helado y frutos rojos"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 13),
  ('menu-pizza-party', 'menu-pizza-party', 'Menú "Pizza party"', 'Recepción con mesa de campo, empanadas de carne criollas, dips, brusquetas, mini tarteletas y albondiguitas. La comida: pizzas de diferentes tipos — muzarella, napolitana, primavera, jamón y morrones, fugazzeta y ananá. Postre a elección.', 2900000, 'ARS', '[{"url":"/photos/pizza-party-1.jpg","alt":"Menú \"Pizza party\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Recepción: mesa de campo + empanadas criollas","Dips, brusquetas, mini tarteletas y albondiguitas","Pizzas: muzarella, napolitana, primavera, jamón y morrones, fugazzeta, ananá","Postre a elección: crumble de manzana con helado o brownie con helado y frutos rojos"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 14),
  ('menu-comida-criolla', 'menu-comida-criolla', 'Menú "Comida criolla"', 'Entrada: tabla de fiambres con 3 quesos, salames, jamón natural y crudo, pan de campo y empanadas salteñas cortadas a cuchillo. Principal a elección: guiso casero de lentejas pardinas con chorizo ahumado, panceta y verduras, o carbonada criolla con carne, papas, batatas, zapallo, choclo y orejones de durazno. Servido en cazuelas de barro norteñas.', 3200000, 'ARS', '[{"url":"/photos/comida-criolla-1.jpg","alt":"Menú \"Comida criolla\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Entrada: tabla de fiambres, pan de campo, empanadas salteñas","Opción 1: guiso de lentejas pardinas","Opción 2: carbonada criolla","Servido en cazuelas de barro norteñas"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 15),
  ('menu-encuentro', 'menu-encuentro', 'Menú "Encuentro"', 'Recepción con mesa de campo (fiambres, quesos, dips de hummus y berenjenas en escabeche, panes, tostaditas saborizadas, grisines, batatitas fritas y crackers). La comida: 2 por persona — empanadas salteñas de carne, canastitas de verdura y canastitas caprese.', 2300000, 'ARS', '[{"url":"/photos/empanadas-1.jpg","alt":"Menú \"Encuentro\" — Umami Bites Catering"},{"url":"/photos/picada-encuentro-1.jpg","alt":"Menú \"Encuentro\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Recepción: mesa de campo completa","Panes, tostaditas, grisines y batatitas fritas","2 por persona: empanadas salteñas + canastitas de verdura y caprese"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 16),
  ('menu-mesa-campo', 'mesa-de-campo-umami', 'Mesa de campo "Umami"', 'Tabla de fiambres y quesos, dips de distintos sabores (hummus de garbanzo y morrón asado, baba ganush, crema ciboulette, queso crema con verdeo, pasta de aceituna), brusquetas variadas, mini tarteletas de rockefort y nuez y albondiguitas de poroto rojo y garbanzo.', 2600000, 'ARS', '[{"url":"/photos/p04.jpg","alt":"Mesa de campo \"Umami\" — Umami Bites Catering"},{"url":"/photos/p12.jpg","alt":"Mesa de campo \"Umami\" — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Tabla de fiambres y quesos","Dips de diferentes sabores","Brusquetas variadas + mini tarteletas de rockefort y nuez","Albondiguitas de poroto rojo y garbanzo"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20"}'::jsonb, 17),
  ('menu-isla-saludable', 'isla-saludable', 'Isla saludable', 'Muffins integrales (cacao, remolacha, zuccini, chocolate blanco), bandeja de frutas de estación, barras de cereal, tostadas de pan integral con semillas, dulce casero, queso untable, tabla de quesos, mix de frutos secos, licuados, jugo de naranja exprimido y yogurt casero con granola.', 600000, 'ARS', '[{"url":"/photos/isla-saludable-1.jpg","alt":"Isla saludable — Umami Bites Catering"},{"url":"/photos/isla-saludable-2.jpg","alt":"Isla saludable — Umami Bites Catering"}]'::jsonb, true, 300, 'Menús', 'package', 1, '["Muffins integrales + barras de cereal","Frutas de estación y frutos secos","Yogurt casero con granola y licuados","Tabla de quesos y dulce casero"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","tipo":"Complemento saludable"}'::jsonb, 18),
  ('menu-brunch', 'menu-brunch', 'Brunch', 'Salados: chips de pan blanco y negro con fiambres, sanwichitos de miga, scons salados, pizzetas o medialunas calientes y tabla de fiambres. Dulce: alfajorcitos, brownies, apple crumble, lemonies, torta a elección (1 cada 10 personas), muffins variados y fruta de estación.', 2400000, 'ARS', '[{"url":"/photos/brunch-1.jpg","alt":"Brunch — Umami Bites Catering"},{"url":"/photos/brunch-2.jpg","alt":"Brunch — Umami Bites Catering"}]'::jsonb, true, 300, 'Brunch', 'package', 1, '["Salados: chips, sanwichitos de miga, scons, pizzetas / medialunas","Tabla de fiambres","Dulce: alfajorcitos, brownies, lemonies, muffins","Torta a elección (1 cada 10 personas) + fruta de estación"]'::jsonb, '{"unit":"persona","tagline":"Por persona · mínimo 20","incluye":"Recepción, comida ppal., bebida sin alcohol, vajilla, mantelería y servicio de mesa"}'::jsonb, 19),
  ('menu-mesa-dulce', 'mesa-dulce', 'Mesa dulce', 'Tortas a elección (brownie con DDL y merengue, masa nuez sublé y frutos rojos, rogel, lemon pie, carrot cake, havanett, chocotorta, key lime pie), petit fours, budines y muffins variados.', 700000, 'ARS', '[{"url":"/photos/mesa-dulce-spread.jpg","alt":"Mesa dulce — Umami Bites Catering"},{"url":"/photos/p20.jpg","alt":"Mesa dulce — Umami Bites Catering"},{"url":"/photos/p30.jpg","alt":"Mesa dulce — Umami Bites Catering"},{"url":"/photos/p33.jpg","alt":"Mesa dulce — Umami Bites Catering"},{"url":"/photos/p32.jpg","alt":"Mesa dulce — Umami Bites Catering"}]'::jsonb, true, 300, 'Mesa dulce', 'package', 1, '["Tortas a elección","Petit fours surtidos","Budines y muffins variados"]'::jsonb, '{"unit":"persona"}'::jsonb, 20),
  ('torta-brownie', 'torta-brownie-ddl', 'Torta Brownie con DDL y merengue', 'Torta brownie con dulce de leche, crema y/o merengue. Tamaño entero para mesa dulce o postre.', 3800000, 'ARS', '[{"url":"/photos/p20.jpg","alt":"Torta Brownie con DDL y merengue — Umami Bites Catering"}]'::jsonb, true, 10, 'Mesa dulce', 'dish', null, null, '{"unit":"torta"}'::jsonb, 21),
  ('torta-frutos-rojos', 'torta-frutos-rojos', 'Torta de frutos rojos', 'Bizcocho con crema y abundantes frutos rojos de estación. Torta entera.', 4200000, 'ARS', '[{"url":"/photos/p33.jpg","alt":"Torta de frutos rojos — Umami Bites Catering"},{"url":"/photos/p24.jpg","alt":"Torta de frutos rojos — Umami Bites Catering"}]'::jsonb, true, 10, 'Mesa dulce', 'dish', null, null, '{"unit":"torta"}'::jsonb, 22),
  ('torta-nuez', 'torta-nuez-ddl', 'Torta de nuez con DDL y crema', 'Torta de masa de nuez con dulce de leche y crema. Opción con frutos rojos. Torta entera.', 4200000, 'ARS', '[{"url":"/photos/p30.jpg","alt":"Torta de nuez con DDL y crema — Umami Bites Catering"},{"url":"/photos/p20.jpg","alt":"Torta de nuez con DDL y crema — Umami Bites Catering"}]'::jsonb, true, 10, 'Mesa dulce', 'dish', null, null, '{"unit":"torta","opcion":"Con frutos rojos: $48.000"}'::jsonb, 23),
  ('torta-key-lime', 'key-lime-pie', 'Key lime pie', 'Tarta de lima con base crocante y crema. Torta entera.', 4800000, 'ARS', '[{"url":"/photos/p32.jpg","alt":"Key lime pie — Umami Bites Catering"}]'::jsonb, false, 10, 'Mesa dulce', 'dish', null, null, '{"unit":"torta"}'::jsonb, 24),
  ('beb-cerveza', 'cervezas-artesanales-x6', 'Cervezas artesanales (six pack)', '6 latas a elección de 470 ml. Línea Antares (Playa Grande, Honey Beer, Scotch roja, Kölsch rubia) y línea Kunstmann (Torobayo).', 2900000, 'ARS', '[{"url":"/photos/bev-cervezas.jpg","alt":"Cervezas artesanales (six pack) — Umami Bites Catering"}]'::jsonb, true, 40, 'Bebidas', 'dish', null, null, '{"unit":"pack","tierMayor":"$58.000 — 12 latas"}'::jsonb, 25),
  ('beb-vino', 'vino-malbec-desfachatados', 'Vino Malbec "Desfachatados"', 'Vino mendocino Bodega Pretexto. Malbec de intenso color violeta, notas a frutos rojos oscuros y buena estructura de taninos.', 2400000, 'ARS', '[{"url":"/photos/bev-vino.jpg","alt":"Vino Malbec \"Desfachatados\" — Umami Bites Catering"}]'::jsonb, true, 24, 'Bebidas', 'dish', null, null, '{"unit":"botella","tierMayor":"$180.000 — la caja (x6)"}'::jsonb, 26),
  ('beb-barra-libre', 'barra-libre-tragos', 'Barra libre de tragos', 'Barra libre de tragos con alcohol: Fernet cola, Campari con naranja, Cuba libre, Gin tonic, Caipirosk, Caipirinha, Daikiris frutales y Gancia. Consultar carta completa.', 1800000, 'ARS', '[{"url":"/photos/barra-tragos.jpg","alt":"Barra libre de tragos — Umami Bites Catering"}]'::jsonb, true, 300, 'Bebidas', 'package', 1, '["Fernet cola, Campari, Cuba libre, Gin tonic","Caipirosk, Caipirinha, Daikiris, Gancia"]'::jsonb, '{"unit":"persona"}'::jsonb, 27)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  price_in_cents = excluded.price_in_cents,
  currency = excluded.currency,
  images = excluded.images,
  available = excluded.available,
  max_quantity = excluded.max_quantity,
  category = excluded.category,
  type = excluded.type,
  servings = excluded.servings,
  includes = excluded.includes,
  metadata = excluded.metadata,
  sort_order = excluded.sort_order;
